#!/usr/bin/python3
from math import *
import sys
import time

def check_if_number(input):
    try:
        value = int(input)
    except ValueError:
        try:
            value = float(input)
        except ValueError:
            return -1
    return value

def error_handler():
    arr = []
    if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
        print("USAGE")
        print("\t./209poll pSize sSize p\n")
        print("DESCRIPTION")
        print("\tpSize\tsize of the population")
        print("\tsSize\tsize of the sample (supposed to be representative)")
        print("\tp\tpercentage of voting intentions for a specific candidate")
        exit(0)
    if (len(sys.argv) != 4):
        exit(84)
    for i in range(1, len(sys.argv)):
        arr.append(check_if_number(sys.argv[i]))
        if (arr[i - 1] < 0):
            exit(84)
    return(arr)

if __name__ == "__main__":
    arr = []
    arr = error_handler()
    exit(0)
