#!/usr/bin/python3
import sys
import math
import time

def check_if_number(input):
    try:
        value = int(input)
    except ValueError:
        try:
            value = float(input)
        except ValueError:
            exit(84)
    return value

def error_handler():
    if (len(sys.argv) != 2):
        exit(84)
    if (sys.argv[1] == "-h"):
        print("USAGE")
        print("\t./204ducks a\n")
        print("DESCRIPTION")
        print("\ta\tconstant")
        exit(0)
    for index in range(1, len(sys.argv)):
        value = check_if_number(sys.argv[index])
    if (value < 0 or value > 2.5):
        exit(84)
    return value

def probability_density(a, t):
    result = a * (-math.exp(-t)) + (4 - 3 * a) * (-1 / 2) * math.exp(-2 * t) + (2 * a - 4) * (-1 / 4) * math.exp(-4 * t)
    return result

def time_back(t, a):
    j = 0
    while (1):
        if (1 + probability_density(a, j / 60) >= t):
            return (j)
        j+=0.001

def get_prob(a, t):
    return (a * math.exp(-t) + (4 - 3 * a) * math.exp(-2 * t) + (2 * a - 4) * math.exp(-4 * t))

def get_aver(a):
    res = float(0)
    t = float(0)
    while (t < 10):
        res += get_prob(a, t) * t / 1000
        t += 0.001
    return (res)

def get_var(a, mu):
    res = float(0)
    t = float(0)
    while (t < 10):
        res += get_prob(a, t) * math.pow((t - mu), 2) / 1000
        t += 0.001
    return (res)

def get_std_dev(a, mu):
    return (math.sqrt(get_var(a, mu)))
def print_time(t):
    min = int(t / 60)
    sec = int(round(t - 60 * min))
    print(str(min) + "m ", end="")
    print(str(sec) + "s")

def print_time_bis(t):
    min = int(t / 60)
    sec = int(t % 60)
    print(str(min) + "m ", end="")
    print(format(sec, "02d") + "s")

if __name__ == "__main__":
    value = error_handler()
    print("Average return time: ", end="")
    print_time(get_aver(float(value)) * 60)
    print("Standard deviation: ", end="")
    print("%.3f" %(get_std_dev(value, get_aver(value))))
    print("The time after which 50% of the ducks are back: ", end="")
    print_time_bis(time_back(0.50, value))
    print("The time after which 99% of the ducks are back: ", end="")
    print_time_bis(time_back(0.99, value))
    print("Percentage of ducks back after 1 minute: %.1f%%" %((1 + probability_density(value, 1)) * 100))
    print("Percentage of ducks back after 2 minutes: %.1f%%" %((1 + probability_density(value, 2)) * 100))
    exit(0)