#!/usr/bin/python3
from math import *
import sys
import time
import linecache
import csv

def sum_x(file, country):
    index = 0
    row_line = 0
    x = 0
    x_index = 1
    index2 = 0
    index3 = 0
    max_index = 0

    for row in file:
        if (row[1] == country):
            row_line = index
        index += 1
    for col in file[row_line]:
        if (check_if_number(col) != -1):
            max_index = index2
        index2 += 1
    for col in file[row_line]:
        if (index3 >= 2 and index3 - 1 <= max_index):
            x += x_index
            x_index += 1
        index3 += 1
    return x

def sum_y(file, country):
    index = 0
    row_line = 0
    y = 0

    for row in file:
        if (row[1] == country):
            row_line = index
        index += 1
    for col in file[row_line]:
        if (check_if_number(col) != -1):
            y = y + int(col)
    return y

def sum_y_square(file, country):
    index = 0
    row_line = 0
    y = 0

    for row in file:
        if (row[1] == country):
            row_line = index
        index += 1
    for col in file[row_line]:
        if (check_if_number(col) != -1):
            y = y + pow(int(col), 2)
    return y

def sum_x_square(file, country):
    index = 0
    row_line = 0
    x = 0
    x_index = 1
    index2 = 0
    index3 = 0
    max_index = 0

    for row in file:
        if (row[1] == country):
            row_line = index
        index += 1
    for col in file[row_line]:
        if (check_if_number(col) != -1):
            max_index = index2
        index2 += 1
    for col in file[row_line]:
        if (index3 >= 2 and index3 - 1 <= max_index):
            x += pow(x_index, 2)
            x_index += 1
        index3 += 1
    return x

def sum_x_y(file, country):
    index = 0
    row_line = 0
    x_index = 1
    xy = 0

    for row in file:
        if (row[1] == country):
            row_line = index
        index += 1
    for col in file[row_line]:
        if (check_if_number(col) != -1):
            xy = xy + int(col) * x_index
            x_index += 1
    return xy

def check_if_number(input):
    try:
        value = int(input)
    except ValueError:
        try:
            value = float(input)
        except ValueError:
            return -1
    return value

def error_handler():
    arr = []
    if (len(sys.argv) == 2 and sys.argv[1] == "-h"):
        print("USAGE")
        print("\t./207demography code [...]\n")
        print("DESCRIPTION")
        print("\tcode\t country code")
        exit(0)
    if (len(sys.argv) == 1):
        exit(84)
    for i in range(1, len(sys.argv)):
        arr.append(sys.argv[i])
    return(arr)

def print_countries(arr, file):
    i = 1
    print ("Country: ", end='')
    #print (len(arr))
    for row in file:
        for arg in arr:
            #print (row[1] +" and " + arg)
            if (row[1] == arg and i != len(arr)):
                i = i + 1
                print (row[0] + ", ", end='')
            elif (row[1] == arg):
                print (row[0])

def read_file():
    my_file = open("207demography_data.csv")
    file_reader = csv.reader(my_file, delimiter=';')
    return list(file_reader)

if __name__ == "__main__":
    arr = []
    arr = error_handler()
    file = read_file()
    print_countries(arr, file)
    print(sum_x_y(file, arr[0]))
    exit(0)
